name: ci-golang-workflow
on: 
  pull_request:
    branches: 
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    steps:
      - name: Test CI 
        uses: actions/checkout@v2
        uses: actions/setup-go@v2
        with: 
          go-version: 1.17.5
      - run: go env -w GO111MODULE=auto
      - run: cd ci && go test
      - run: cd ci && go run math.go

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: false
          tags: thpfdev1123/fc2.0-ci-go:latest